require 'nokogiri'
require 'open-uri'
require 'pry'
require 'colorize'
require 'ascii'
require 'artii'

require_relative '../lib/bootcamp_app/version'
require_relative '../lib/bootcamp_app/cli'
require_relative '../lib/bootcamp_app/scraper'
require_relative '../lib/bootcamp_app/bootcamp'
